/** Responsive WebP variants generated by scripts/optimize-images.mjs (…/w/<name>-<width>.webp). */
import manifest from '@/data/image-variants.json'

const WIDTHS = [480, 768, 1200, 1600] as const

type Variant = { w: number[]; full: number }
const VARIANTS = manifest as Record<string, Variant>

function variants(src: string) {
  const m = src.match(/^(.*)\/([^/]+)\.(jpe?g|png)$/i)
  if (!m) return null
  const [, dir, name] = m
  return { dir: `${dir}/w`, name, key: `${dir}/${name}` }
}

/**
 * Returns `srcSet`/`sizes`-ready descriptors, or undefined for assets without variants.
 * Only widths that were actually generated are listed — sources narrower than a step have no
 * file there, and a 404 candidate would leave high-DPR phones with a broken image.
 */
export function srcSetFor(src: string, maxWidth = 2048): string | undefined {
  const v = variants(src)
  if (!v) return undefined
  const known = VARIANTS[v.key]
  const fullW = Math.min(known?.full ?? maxWidth, maxWidth)
  const list = (known?.w ?? WIDTHS).filter((w) => w < fullW).map((w) => `${v.dir}/${v.name}-${w}.webp ${w}w`)
  list.push(`${v.dir}/${v.name}-full.webp ${fullW}w`)
  return list.join(', ')
}

/** Smallest WebP for a given target width — handy for tiny thumbnails. */
export function webpFor(src: string, width: (typeof WIDTHS)[number] | 'full' = 'full'): string {
  const v = variants(src)
  return v ? `${v.dir}/${v.name}-${width}.webp` : src
}

/**
 * Always serves the 1080p rendition on every device. The 720p companion from
 * scripts/optimize-videos.mjs is used only when the visitor has explicitly enabled data saver.
 */
let smallVideo: boolean | undefined
export function videoSrcFor(src: string): string {
  if (smallVideo === undefined) {
    if (typeof window === 'undefined') return src
    const nav = navigator as Navigator & { connection?: { saveData?: boolean } }
    smallVideo = Boolean(nav.connection?.saveData)
  }
  return smallVideo ? src.replace(/\.mp4$/, '-720.mp4') : src
}
